### ISSUE TITLE
Modules in an assembly prepared by Naggum.Assembler

### ISSUE THREAD

**Issue by ForNeVeR** [codingteam/naggum#58]
_(See [Naggum.Test/InstructionTests.fs](https://github.com/codingteam/naggum/pull/39/files#diff-ab898889c230e6089a5b9b875ee5191dR24).)_

Currently there are more managed modules than I expected (and I expected exactly one module). We need to check if we're doing everything right and document that behavior.

_Note:_ not sure if it a bug and/or something we need to enhance, so filed as both a bug and an enhancement.

**Comment by Newlifer** [comment]
I second this!

**Comment by rexim** [comment]
*ЧПОК*

**Comment by ForNeVeR** [comment]
Это же мистер Чпокерман! Все в машину!
